config/routes.rb
Rails.application.routes.draw do
  resources :questions do
    resources :answers
  end

  resources :users
  resources :sessions

  get '/logout', to: "sessions#destroy"
  root 'questions#index'
end

app/models/answer.rb
class Answer < ApplicationRecord
  belongs_to  :question
  # belongs_to  :question, foreign_key: :best_answer_id
  belongs_to  :user
  validates   :body, presence: true
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/question.rb
class Question < ApplicationRecord
  belongs_to  :author, class_name: "User"
  has_many    :answers
  # has_one     :best_answer, class_name: "Answer"
  validates   :title, :body, presence: true

end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  has_many :posts, foreign_key: :author_id
  has_many :answers
end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController
  def create
    @question = Question.find(params[:question_id])

    @answer = @question.answers.new(answer_params)
    @answer.user_id = session[:user_id]
    @answer.save
    redirect_to question_path(@question)
  end

  private
    def answer_params
      params.require(:answer).permit(:body)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  def index
    @questions = Question.all.order('created_at DESC')
  end

  def new
    @question = Question.new
  end

  def create
    @question = Question.new(question_params)
    @question.author_id = session[:user_id]
    if @question.save
      redirect_to root_path
    else
      render 'new'
    end
  end

  def show
    @question = Question.find(params[:id])
  end

  private
    def question_params
      params.require(:question).permit(:title, :body)
    end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
    @user = User.new
    # render 'new'
  end

  def create
    @user = User.find_by(username: params[:session][:username])

    if @user
      if @user.authenticate(params[:session][:password])
        session[:user_id] = @user.id
        redirect_to root_path
      else
        render 'new'
      end
    else
      render 'new'
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_path
  end


end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    @user.save
    session[:user_id] = @user.id
    redirect_to root_path
  end

  private
    def user_params
      params.require(:user).permit(:username, :password)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def logged_in?
    !!current_user
  end
end

app/helpers/session_helpers.rb
module SessionHelper

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def logged_in?
    !!current_user
  end

end

helpers SessionHelper

app/views/answers/_answer.html.erb
<div class="answers-container">
  <div class="answer-content">
    <p><%= answer.body %></p>
    <small><%= time_ago_in_words(answer.created_at) %> ago</small>
    <hr>
  </div>
</div>

app/views/answers/_form.html.erb
<div class="answer-wrapper">
  <%= form_for([@question, @question.answers.build], remote: true) do |f| %>
    <p>
      <%= f.label :body %>
      <%= f.text_area :body %>
    </p>

    <p>
      <%= f.submit %>
    </p>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>OverflowClone</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div id="headers">
      <button class="button"><%= link_to 'Home', root_path %></button>
      <% if logged_in? %>
        <button class="button"><%= link_to 'Logout', logout_path%></button>
       <button class="button"><%= link_to 'New Question', new_question_path, id: "new_question", remote: true %></button>
      <% else %>
        <button class="button"><%= link_to 'Sign Up', new_user_path %></button>
        <button class="button"><%= link_to 'Login', new_session_path %></button>
      <% end %>
    </div>
    <%= yield %>
  </body>
</html>

app/views/questions/_form.html.erb
<%= form_for @question, remote: true do |f| %>
  <% if @question.errors.any? %>
    <div class="errors">
      <b><%= pluralize(@question.errors.count, 'error') %> prohibited this form from being saved:</b>
      <ul>
        <% @question.errors.full_messages.each do |error| %>
        <li> <%= error %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <p>
    <%= f.label :title%>
    <%= f.text_field :title %>
  </p>

  <p>
    <%= f.label :body %>
    <%= f.text_area :body%>
  </p>

  <p><%= f.submit %> </p>
<% end %>

app/views/questions/index.html.erb
<div class="questions-container">
  <h1>Questions</h1>
  <% @questions.each do |question| %>
    <div class="question-wrapper">
      <h3><%=link_to question.title, question  %></h3>
      <small><%= question.created_at.strftime('%B %d %Y') %> </small>
    </div>
  <%end  %>
</div>

app/views/questions/new.html.erb
<div class="question-wrapper">
  <h1>New Question</h1>
  <%= render 'form' %>
</div>

app/views/questions/new.js.erb
$('#new_question').after('<%= j render("form") %>');

app/views/questions/show.html.erb
<div class="question-container">
    <h1><%= @question.title %></h1>
    <small class="date"> Submitted at: <%= time_ago_in_words(@question.created_at) %> ago </small>

    <p><%= @question.body %> </p>
</div>

<div class="answers">
  <hr>
  <h2><%= @question.answers.count %> Answers: </h2>
  <%= render @question.answers %>

  <h3>Add an Answer:</h3>
  <%= render 'answers/form' %>
</div>

app/views/users/new.html.erb
<div class="user-form">
  <%= form_for @user do |f| %>
  <p>
    <%= f.label :username %>
    <%= f.text_field :username %>
  </p>

  <p>
    <%= f.label :password %>
    <%= f.password_field :password %>
  </p>

  <p>
    <%= f.submit %>
  </p>
  <% end %>
</div>